name: oref
description: Oref is a lightweight, high-performance reactive programming library.
version: 0.5.0
repository: https://github.com/odroe/odroe/tree/main/pub/oref
homepage: https://odroe.dev/packages/oref
documentation: https://odroe.dev/docs/oref/get-started
issue_tracker: https://github.com/odroe/odroe/issues
resolution: workspace

funding:
  - https://github.com/sponsors/medz

topics:
  - state
  - reactive
  - ref
  - derived
  - effect

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
