name: oncecall
description: >-
  Oncecall is a memoization tool for use in the build method of Widgets.
version: 0.0.2
repository: https://github.com/odroe/odroe/tree/main/pub/oncecall
homepage: https://odroe.dev/packages/oncecall
documentation: https://odroe.dev/docs/oncecall
issue_tracker: https://github.com/odroe/odroe/issues
resolution: workspace

funding:
  - https://github.com/sponsors/medz

topics:
  - once
  - call
  - memo

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  _octr: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
