name: setup
description: Dart Setup widget
version: 0.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  oinject: ^0.1.2
  oref: ^0.4.1

dev_dependencies:
  flutter_lints: ^5.0.0
